#@host = blog.1vadimhladchenko.repl.co
@host = 3000-copper-peacock-recgkxr0.ws-eu18.gitpod.io
@cookie = _gitpod_io_=s:55c0c7b1-c3f0-4f82-bf45-8b5f9196041d.Qh73rZH0wd0QKQpzAjNvLo0b0KLBNPGyb+5GYa1If6Q; gitpod-user=loggedIn; _gitpod_io_ws_d1549758-af6a-439b-bad8-0e7afdea9c94_owner_=Bzm5DGW0gH_ndm5iVywE.BbZsQXDNypQ; _gitpod_io_ws_f98462a1-be20-4222-a58a-00c5845f3f63_owner_=7uYw.xcStArbJXJT803KL7ArMGh39dN5; _gitpod_io_ws_252cc01f-6fe7-4995-a83b-e6c18dc13c92_owner_=iCcLsnFE8Ua.E0iQRDkggmfF9.jwNlOS; _gitpod_io_ws_6f8053b4-db20-4632-b3cd-b7dbf909230b_owner_=M0oSYm_xSlbXfO_Xz5XBlH9rzLirll0k

@auth_user = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjYxNWFmODM3MjU4OGVmYjg2ZDI0NDdmYSIsImlhdCI6MTYzMzUyMzUwN30.VKKboQk9JPyaFXbULpYEDW5bEo8pM6L6uWAL6nRTEj8
@auth_root = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxNWQ2YWY0ODBiNzJiNmIxZjdkYWZmNiIsImlhdCI6MTYzMzUyNDk4OX0.JPAnfRCQ3_cAUIJz83Q4aREObLJ2sftdT9HSnj8sek8

###
GET https://{{host}}/api/blogs/
cookie: {{cookie}}
###
GET https://{{host}}/api/users/
cookie: {{cookie}}
###
GET https://{{host}}/api/blogs/w61547aadd8c80c69a748e944
###
POST https://{{host}}/api/blogs/
Content-Type: application/json
Auth1orization: Bearer {{auth_root}}
cookie: {{cookie}}

{
  "title": "Test Authorization error",
  "author": "Root",
  "url": "127.0.0.52",
  "likes": 1
}

###
PUT https://{{host}}/api/blogs/615571b043352a3550187f3e
Content-Type: application/json
cookie: {{cookie}}
Auth1orization: Bearer {{auth_user}}

{

  "likes": "1"
}
###
POST https://{{host}}/api/users/
Content-Type: application/json
cookie: {{cookie}}

{
  "username": "root",
  "name": "Super user",
  "password": "qazwsx"
}
###
DELETE https://{{host}}/api/blogs/615d8fa9f2a52f21af53d96b
cookie: {{cookie}}
Authorization: Bearer {{auth_root}}

###
POST https://{{host}}/api/login/
Content-Type: application/json
cookie: {{cookie}}

{
  "username" : "user",
  "password" : "qwerty"
}
###
POST https://{{host}}/api/login/
Content-Type: application/json
cookie: {{cookie}}

{
  "username": "root",
  "password": "qazwsx"
}